import Head from 'next/head'
import Section from '../components/about_me/section/Section'



export default function Home() {
  return (
    <>

      <Head>
        <title>About me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section pos={"left"}>


      </Section>




    </>

  )
}
